### ISSUE TITLE
xmind2020@2021.5.27: hash check failed

### ISSUE THREAD

**Issue by lxingh** [naderi/scoop-bucket#14]

**Comment by naderi** [comment]
Fixed.
@lxingh Thank you or reporting.

**Comment by lxingh** [comment]
PS C:\Windows\System32> scoop install naderi/xmind2020 -g
Installing 'xmind2020' (2021.5.27) [64bit]
dl.7z (92.1 MB) [=============================================================================================] 100%
Checking hash of dl.7z ... ERROR Hash check failed!
App:         naderi/xmind2020
URL:         https://www.xmind.net/zen/download/win64/#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    d2b3ab584c2fe676e7b32246d0e52fdb964c74745f36fffe5ff4a2590f854180
Actual:      93b58da27622b01c366492164392ea6b2e8c84f700159547158130c0bb7b1a74

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/naderi/scoop-bucket/issues/new?title=xmind2020%402021.5.27%3a+hash+check+failed

**Comment by lxingh** [comment]
@naderi
PS C:\Windows\System32> scoop install naderi/xmind2020 -g
Installing 'xmind2020' (2021.5.27) [64bit]
dl.7z (92.1 MB) [=============================================================================================] 100%
Checking hash of dl.7z ... ERROR Hash check failed!
App:         naderi/xmind2020
URL:         https://www.xmind.net/zen/download/win64/#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    d2b3ab584c2fe676e7b32246d0e52fdb964c74745f36fffe5ff4a2590f854180
Actual:      93b58da27622b01c366492164392ea6b2e8c84f700159547158130c0bb7b1a74

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/naderi/scoop-bucket/issues/new?title=xmind2020%402021.5.27%3a+hash+check+failed

**Comment by naderi** [comment]
@lxingh Please run:
scoop cache rm *
scoop update *
scoop install xmind2020
