### ISSUE TITLE
teracopy@3.8.5: Decompress error

### ISSUE THREAD

**Issue by Hxppdv** [naderi/scoop-bucket#18]
Failed to extract files from D:\Scoop\apps\teracopy\3.8.5\teracopy.exe#tera.exe.
Log file:
  D:\Scoop\apps\teracopy\3.8.5\innounp.log

[innounp.log](https://github.com/naderi/scoop-bucket/files/6818217/innounp.log)

**Comment by naderi** [comment]
@Hxppdv Thank yo for reporting.
Please run:
scoop uninstall teracopy
scoop cache rm *
scoop update teracopy
scoop install teracopy
