### ISSUE TITLE
xmind2020@2021.01.07: decompress error

### ISSUE THREAD

**Issue by lxingh** [naderi/scoop-bucket#3]
Installing 'xmind2020' (2021.01.07) [64bit]
Loading dl.7z from cache
Checking hash of dl.7z ... ok.
Extracting dl.7z ... done.
Running installer script...
ERROR Exit code was 2!
Failed to extract files from D:\Scoop\apps\xmind2020\2021.01.07\$PLUGINSDIR\app-64.7z.
Log file:
  D:\Scoop\apps\xmind2020\2021.01.07\$PLUGINSDIR\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/naderi/scoop-bucket/issues/new?title=xmind2020%402021.01.07%3a+decompress+error

**Comment by naderi** [comment]
Hi @lxingh,
Thank you for reporting!
It fixed.
Please run:
`scoop uninstall xmind2020`
and then:
`scoop install xmind2020`
