### ISSUE TITLE
epicgames@nightly: decompress error

### ISSUE THREAD

**Issue by rafi0** [naderi/scoop-bucket#37]
PS C:\Users\Msi> scoop install epicgames
WARN  Purging previous failed installation of epicgames.
ERROR 'epicgames' isn't installed correctly.
Removing older version (nightly-20220519).
'epicgames' was uninstalled.
WARN  This is a nightly version. Downloaded files won't be verified.
Installing 'epicgames' (nightly-20220519) [64bit]
EpicGamesLauncherInstaller.msi (151,5 MB) [==============================================================================================================================] 100%
Extracting EpicGamesLauncherInstaller.msi ... ERROR Exit code was 1603!

**Comment by naderi** [comment]
Hi @rafi0:
For me it works like a charm:

![image](https://user-images.githubusercontent.com/27568/169271766-9a870e10-b1f0-4311-81c9-ec3fcc1121f6.png)

Try this commands:
```
scoop uninstall epicgames -p
scoop cache rm *
scoop update *
scoop install epicgames
```
