### ISSUE TITLE
 Could not find 'smplayer-portable-19.5.0.0'! (error 16)

### ISSUE THREAD

**Issue by suburbanbourbon** [naderi/scoop-bucket#38]
Trying to install smplayer version 22.2.0 in the .json the version is correct but the extract dir is not.
https://github.com/naderi/scoop-bucket/blob/fdce4d9c9f107f0a10535341db0f2770d0cbba9c/bucket/smplayer.json#L15=

hence the error

**Comment by naderi** [comment]
Hi @suburbanbourbon ,
Thank you for reporting.
It is fixed now.
