### ISSUE TITLE
cpdf@2.4: hash check failed

### ISSUE THREAD

**Issue by NSP-0123456** [naderi/scoop-bucket#39]
App:         naderi/cpdf                                                                          
URL:         https://github.com/coherentgraphics/cpdf-binaries/raw/master/Windows64bit/cpdf.exe   
First bytes: 4D 5A 90 00 03 00 00 00                                                              
Expected:    d9951f5b6c8a17835c5fd10b41cfd4c5915291fde171bc050b5a14900426dd96                     
Actual:      0160491b8a6108ebde415b58b398e5a7449c45de9643e9d99f6e030e797dec3e

**Comment by naderi** [comment]
@NSP-0123456 Thank you for the report. Fixed!
