### ISSUE TITLE
totalcommander-portable@11.00: Hash check failed

### ISSUE THREAD

**Issue by ZzZombo** [naderi/scoop-bucket#48]
Hash check failed!
App:         3dparty-naderi/totalcommander-portable
URL:         https://www.totalcommander.ch/win/tcmd1100x64.exe
First bytes: 77 90 144 0 3 0 0 0
Expected:    085d171d8a9af4b56ebd90ce23e3c5c5b092470e338cc5333b7061b0f20828cd
Actual:      9928f1fc20924d3ab3f9edb958b7205c1982077eeb5b1f10fa7072dad358a104

**Comment by naderi** [comment]
@ZzZombo Thank you for reporting.
It fixed.
