### ISSUE TITLE
Regtool new version 1.348

### ISSUE THREAD

**Issue by NSP-0123456** [naderi/scoop-bucket#50]
update version nb - 1.348
update hashes : 
644e68182916d9ff1e43d177bb1121e7ccb2e877595e42ffe146fe8d19e98120 *RegCoolX32.zip
0bc6a5517deda2b0d26ce68c404eddf9f9fb3f46e5bc4d18d5ba611195e5fd06 *RegCoolX64.zip

**Comment by naderi** [comment]
@NSP-0123456 Thank you for reporting. It's now updated to 1.348.
