### ISSUE TITLE
wiztree update to 4.16

### ISSUE THREAD

**Issue by NSP-0123456** [naderi/scoop-bucket#51]
Change version to 4.16
change hash to:
336c6ff43c0b4722de45517192ded99a6cff1a86b9132c25e4c00a3031c7e0e *wiztree_4_16_portable.zip

**Comment by NSP-0123456** [comment]
seems updated in extras

**Comment by naderi** [comment]
@NSP-0123456 Thank you for reporting.
I have deleted the WizTree manifest from my buckets, because it already exists in extras.
